//
//  FoodImageOrigin.swift
//  GYM APP
//

import Foundation

/// Describes the origin of a food image stored in FoodImage.
///
/// Used to distinguish how the image was obtained so that the UI can
/// show appropriate indicators and apply correct replacement rules.
/// A nil imageOrigin on FoodImage means the record predates Phase 37B.
enum FoodImageOrigin: String, Codable, Hashable, Sendable, CaseIterable {
    /// Photo uploaded directly by the user (camera or photo library).
    case userUploaded  = "userUploaded"
    /// Image generated by an AI image generation service.
    case aiGenerated   = "aiGenerated"
    /// Image sourced from the app's built-in food catalog assets.
    case catalog       = "catalog"
    /// System placeholder — no real image is available yet.
    case placeholder   = "placeholder"

    var displayName: String {
        switch self {
        case .userUploaded: return "Foto propia"
        case .aiGenerated:  return "Generada por IA"
        case .catalog:      return "Catálogo"
        case .placeholder:  return "Marcador"
        }
    }

    /// Returns true when the image was created by an automated source and
    /// must not silently overwrite a user-uploaded photo.
    var isAutomated: Bool {
        switch self {
        case .aiGenerated, .catalog, .placeholder: return true
        case .userUploaded:                        return false
        }
    }
}
