//
//  FoodImageGenerationState.swift
//  GYM APP
//

import Foundation

/// Tracks the lifecycle of an AI image generation request for a FoodImage.
///
/// Only relevant when FoodImage.imageOrigin == .aiGenerated.
/// A nil aiGenerationState on FoodImage means the image was not generated by AI.
enum FoodImageGenerationState: String, Codable, Hashable, Sendable, CaseIterable {
    /// A generation request has been submitted and is waiting to be processed.
    case pending    = "pending"
    /// The provider is actively generating the image.
    case generating = "generating"
    /// The image was generated successfully and is stored on disk.
    case ready      = "ready"
    /// Generation failed. The error is logged but not stored in the model.
    case failed     = "failed"

    var displayName: String {
        switch self {
        case .pending:    return "En cola"
        case .generating: return "Generando"
        case .ready:      return "Lista"
        case .failed:     return "Error"
        }
    }

    var isTerminal: Bool {
        switch self {
        case .ready, .failed: return true
        case .pending, .generating: return false
        }
    }
}
